openapi: 3.0.0
info:
  version: 1.0.0
  title: Demo Api

paths:
  /myModels:
    get:
      operationId: listMyModels
      responses:
        200:
          description: Resource list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MyModel'

###############################################################################
components:

  schemas:

    MyModel:
      properties:
        someProperty:
          type: string
